Repository hanami/controller, pull requests merged in 2018-07, with the labels that each got.

#261 remove parsed_request_body
  lib/hanami/action.rb
  lib/hanami/action/request.rb
  spec/unit/hanami/action_spec.rb
Labels: breaking-change

#263 Remove body cleanup for head
  lib/hanami/action.rb
  spec/integration/hanami/controller/full_stack_spec.rb
  spec/integration/hanami/controller/head_spec.rb
  spec/support/renderer.rb
Labels: breaking-change

#262 deprecate parsed_request_body
  Gemfile
  lib/hanami/action/rack.rb
  spec/unit/hanami/action_spec.rb
Labels: deprecation

#268 Remove body cleanup for http status without body
  lib/hanami/action.rb
  spec/integration/hanami/controller/head_spec.rb
Labels: breaking-change

#267 fix double flash bug, flash#empty?, flash#each and flash#map
  lib/hanami/action/flash.rb
  lib/hanami/action/session.rb
  spec/integration/hanami/controller/flash_spec.rb
  spec/integration/hanami/controller/full_stack_spec.rb
  spec/support/fixtures.rb
Labels: fix

#270 Code quality tools
  .circleci/config.yml
  .jrubyrc
  .travis.yml
  Gemfile
  README.md
  Rakefile
  script/ci
  spec/spec_helper.rb
  spec/support/isolation_spec_helper.rb
Labels: enhancement
