Repository hanami/controller, pull requests merged in 2019-06, with the labels that each got.

#289 Do not error when If-Modified-Since is set but no validation exists for it
  lib/hanami/action/cache/conditional_get.rb
  spec/integration/hanami/controller/cache_spec.rb
Labels: bug, fix

#283 Fix broken 404 links to guides.hanamirb.org
  README.md
  lib/hanami/action/params.rb
  lib/hanami/action/validatable.rb
Labels: documentation

#294 Drone CI
  .drone.yml
  script/test
Labels: enhancement
