Repository hanami/controller, pull requests merged in 2020-09, with the labels that each got.

#315 Fix mime type acceptance
  lib/hanami/action/mime.rb
  spec/integration/hanami/controller/mime_type_spec.rb
  spec/support/fixtures.rb
Labels: fix

#326 Rationalize flash behavior
  lib/hanami/action/flash.rb
  lib/hanami/action/response.rb
  lib/hanami/action/session.rb
  lib/hanami/action/standalone_action.rb
  lib/hanami/controller.rb
  spec/integration/hanami/controller/flash_spec.rb
  spec/support/renderer.rb
  spec/unit/hanami/action/flash_spec.rb
  spec/unit/hanami/action/session_spec.rb
  spec/unit/hanami/action_spec.rb
Labels: enhancement, fix

#327 Reintroduce CSRFProtection module
  lib/hanami/action/csrf_protection.rb
  spec/unit/hanami/action/csrf_protection_spec.rb
Labels: enhancement
